### ISSUE TITLE
License Conflict

### ISSUE THREAD

**Issue by jufemaiz** [sjauld/go-abn#8]
>     cobra    (LATEST)   policy_conflict

Ref: https://app.fossa.io/projects/git%2Bgithub.com%2Fsjauld%2Fgo-abn/refs/branch/master/3ecb4006de214af074c55c298bdc9cf07db44dbf/preview

**Comment by sjauld** [comment]
Ok so cobra's not actually licenced undel AGPL, it provides an init utility that enables you to licence your software using a number of options including AGPL. I'll work out how to whitelist this in the scan.
